import { StyleSheet} from "react-native";
import { fonts } from "../constants";
import { 
    responsiveScreenHeight as SH,
    responsiveScreenWidth as SW,
    responsiveScreenFontSize as RF,
  } from 'react-native-responsive-dimensions';
  import colors from "../constants/colors";
export default StyleSheet.create({
    container: {
        flex: 1,
    },
    header: {
        width: SW(100),
        height: SH(8),
        backgroundColor: colors.WHITE_COLOR,
        justifyContent: 'space-around',
        flexDirection: 'row',
        alignItems: 'center',
    },
    header_box: {
        width: SW(25),
        height: SH(7),
        justifyContent: 'center',
        alignItems: 'center',
    },
    headerText: {
        fontSize: RF(2.5),
        fontFamily: fonts.PoppinsSemiBold,
        color: colors.MAIN_THEME_COLOR,
        textAlign: 'left',
        marginTop: SH(2),
        marginLeft: SW(2),
    },
    dashImage: {
        width: SW(40),
        height: SW(40),
        alignSelf: 'center',
        resizeMode: 'contain',
        marginTop: SH(3),
    },
    LabelText: {
        fontSize: RF(2),
        fontFamily: fonts.PoppinsSemiBold,
        color: colors.MAIN_THEME_COLOR,
        textAlign: 'left',
        marginTop: SH(3),
        marginLeft: SW(2),
        alignSelf: 'center',
    },
    card_d: {
        width: SW(70),
        height: SH(6),
        backgroundColor: colors.MAIN_THEME_COLOR_50,
        borderRadius: 15,
        alignSelf: 'center',
    },
    valueText: {
        fontSize: RF(2.2),
        fontFamily: fonts.PoppinsSemiBold,
        color: colors.BLACK_COLOR,
        textAlign: 'center',
        marginTop: SH(1.5),
    },
    TitleText: {
        fontSize: RF(2.5),
        fontFamily: fonts.PoppinsBold,
        color: colors.MAIN_THEME_COLOR,
        textAlign: 'left',
        marginTop: SH(3),
        marginLeft: SW(2),
        alignSelf: 'center',
    },
    card_dd: {
        width: SW(90),
        height: SH(10),
        backgroundColor: colors.WHITE_COLOR,
        borderRadius: 5,
        alignSelf: 'center',
        marginTop: SH(1.2),
        shadowColor: colors.MAIN_THEME_COLOR,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    card_dd_top: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: SH(1),
        paddingHorizontal: SW(4),
    },
    valueText_tt: {
        fontSize: RF(1.8),
        fontFamily: fonts.PoppinsSemiBold,
        textAlign: 'left',
        color: colors.MAIN_THEME_COLOR,
    },
    valueText_t: {
        fontSize: RF(1.6),
        fontFamily: fonts.PoppinsBold,
        textAlign: 'right',
        color: colors.MAIN_THEME_COLOR,
    },
    card_dd_bottom: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: SW(1),
        paddingHorizontal: SW(10),
    },
    valueText_b:{
        fontSize: RF(1.6),
        fontFamily: fonts.PoppinsRegular,
        textAlign: 'left',
        color: colors.MAIN_THEME_COLOR,
    },
    valueText_bb:{
        fontSize: RF(1.6),
        fontFamily: fonts.PoppinsSemiBold,
        color: colors.BLACK_COLOR,
        textAlign: 'right',
    },
    valueText_bbt:{
        fontSize: RF(1.3),
        fontFamily: fonts.PoppinsSemiBold,
        color: colors.MAIN_THEME_COLOR,
        textAlign: 'right',
    },

    // Transaction

    headerText_T:{
        fontSize: RF(2.5),
        fontFamily: fonts.PoppinsSemiBold,
        color: colors.MAIN_THEME_COLOR,
        textAlign: 'left',
        marginTop: SH(2),
        alignSelf: 'center',
    },
    image_T:{
        height: SH(50),
        width: SW(80),
        resizeMode: 'contain',
        marginTop: SH(3),
        alignSelf: 'center',
        marginBottom: SH(3),
    },
    Btn_T:{
        width: SW(70),
        height: SH(7),
        backgroundColor: colors.MAIN_THEME_COLOR,
        borderRadius:SH(3.5),
        alignSelf: 'center',
        marginTop: SH(3),
        shadowColor: colors.BLACK_COLOR,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    BtnText_T:{
        fontSize: RF(2.2),
        fontFamily: fonts.PoppinsSemiBold,
        color: colors.WHITE_COLOR,
        textAlign: 'center',
        marginTop: SH(1.5),
    },
    Btn_TT:{
        width: SW(70),
        height: SH(7),
        backgroundColor: colors.WHITE_COLOR,
        borderRadius:SH(3.5),
        borderColor: colors.MAIN_THEME_COLOR,
        borderWidth: 1,
        alignSelf: 'center',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: SH(3),
        shadowColor: colors.MAIN_THEME_COLOR,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    BtnText_TT:{
        fontSize: RF(2.2),
        fontFamily: fonts.PoppinsSemiBold,
        color: colors.MAIN_THEME_COLOR,
        textAlign: 'center',
        marginTop: SH(1.5),
    },
    centeredView: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: colors.MAIN_THEME_COLOR_50,
    },
    modalView: {
        backgroundColor: 'white',
        width: SW(90),
        height: SH(50),
        borderRadius: 20,
        padding: SW(5),
        alignItems: 'center',
        shadowColor: colors.MAIN_THEME_COLOR,
        shadowOffset: {
          width: 0,
          height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
      },
    modalText: {
        fontSize: RF(2.5),
        fontFamily: fonts.PoppinsSemiBold,
        color: colors.MAIN_THEME_COLOR,
        textAlign: 'center',
    },
    flatlist: {
        height: SH(28),
    },
    closeBtn: {
        width: SW(6),
        height: SW(6),
        backgroundColor: colors.WHITE_COLOR,
        borderRadius: 2,
        alignItems: 'center',
        justifyContent: 'center',
        position: 'absolute',
        alignSelf: 'center',
        top: SW(3),
        right: SW(3)
    },
    closeBtn_del: {
        width: SW(10),
        height: SW(10),
        alignItems: 'center',
        marginTop: SH(2),
    },
    closeBtnText_del: {
        fontSize: RF(2),
        fontFamily: fonts.PoppinsSemiBold,
        color: colors.WHITE_COLOR,
    },
    closeBtnText: {
        fontSize: RF(1.2),
        fontFamily: fonts.PoppinsSemiBold,
        color: colors.MAIN_THEME_COLOR,
    },
    input: {
        width: SW(70),
        height: SH(5),
        borderWidth: 1,
        borderColor: colors.MAIN_THEME_COLOR,
        borderRadius: 10,
        marginTop: SH(2),
        paddingHorizontal: SW(2),
        fontSize: RF(1.6),
        fontFamily: fonts.PoppinsRegular,
        paddingLeft: SW(4),
        color: colors.BLACK_COLOR,
    },
    modalBtn: {
        width: SW(60),
        height: SH(5),
        backgroundColor: colors.MAIN_THEME_COLOR,
        borderRadius: 10,
        marginTop: SH(1),
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalBtnText: {
        fontSize: RF(2),
        fontFamily: fonts.PoppinsSemiBold,
        color: colors.WHITE_COLOR,
    },
//Goals
image_G:{
    height: SH(30),
    width: SW(50),
    resizeMode: 'contain',
    alignSelf: 'center',
    marginBottom: SH(3),
},
card_G:{
    width: SW(90),
    height: SH(10),
    flexDirection:'row',
    justifyContent: 'space-around',
    backgroundColor: colors.MAIN_THEME_COLOR,
    borderRadius: 20,
    alignSelf: 'center',
    alignItems: 'center',
    shadowColor: colors.MAIN_THEME_COLOR,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
},
card_GG:{
    width: SW(41),
    height: SH(8),
    justifyContent: 'center',
    paddingHorizontal: SW(4),
    backgroundColor: colors.WHITE_COLOR,
    borderRadius: 20,
},
LabelText_G:{
    fontSize: RF(2),
    fontFamily: fonts.PoppinsSemiBold,
    color: colors.MAIN_THEME_COLOR,
    textAlign: 'center',
    marginTop: SH(0.5),
},
valueText_G:{
    fontSize: RF(2),
    fontFamily: fonts.PoppinsSemiBold,
    color: colors.BLACK_COLOR,
    textAlign: 'center',
},
Btn_G:{
    width: SW(15),
    height: SW(15),
    bottom: SH(4),
    right: SW(8),
    borderColor: colors.WHITE_COLOR,
    borderWidth: 2,
    backgroundColor: colors.MAIN_THEME_COLOR,
    borderRadius:SH(3.5),
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: colors.BLACK_COLOR,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    position: 'absolute',
},
BtnText_G:{
    fontSize: RF(3),
    fontFamily: fonts.PoppinsSemiBold,
    color: colors.WHITE_COLOR,
    textAlign: 'center',
},
datePicker:{
    width: SW(70),
    height: SH(4),
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignSelf: 'center',
    marginTop: SH(1),
    alignItems: 'center',
    borderRadius: 10,
    shadowColor: colors.MAIN_THEME_COLOR,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 15,
    backgroundColor: colors.WHITE_COLOR,
    borderWidth: 1,
    borderColor: colors.MAIN_THEME_COLOR,
},
datePickerText:{
    fontSize: RF(2),
    fontFamily: fonts.PoppinsSemiBold,
    color: colors.MAIN_THEME_COLOR,
    textAlign: 'center',
},
datePickerValue:{
    fontSize: RF(1.8),
    fontFamily: fonts.PoppinsSemiBold,
    color: colors.BLACK_COLOR,
    textAlign: 'center',
},
TimeText:{
    fontSize: RF(1.5),
    fontFamily: fonts.PoppinsSemiBold,
    color: colors.MAIN_THEME_COLOR,
    textAlign: 'center',
    marginTop: SH(1),
},
feedIcon:{
    width: SW(8),
    height: SW(8),
    resizeMode: 'contain',
    alignSelf: 'center',
    marginTop: SH(1),
    marginRight: SW(4),
},
feedIconr:{
  width: SW(8),
  height: SW(8),
  resizeMode: 'contain',
  alignSelf: 'center',
  marginTop: SH(1),
  marginLeft: SW(4),
},
profilePic: {
    width: SW(80),
    height: SW(40),
    resizeMode: 'contain',
  },
  post_d: {
    width: SW(90),
    height: SH(29),
    backgroundColor: colors.WHITE_COLOR,
    borderTopEndRadius: 6,
    borderTopStartRadius: 6,
    alignSelf: 'center',
    marginTop: SH(1),
    alignItems: 'center',
  },
  post_header: {
    width: SW(90),
    height: SH(8),
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: SW(3),
  },
  postprofPic: {
    width: SW(10),
    height: SW(10),
    borderRadius: SW(5),
    resizeMode: 'cover',
    marginTop: SH(1),
    marginRight: SW(3),
    borderWidth: 1,
    borderColor: colors.BLACK_COLOR_F2,
  },
  PostPc: {
    width: SW(90),
    height: SH(20),
    backgroundColor: 'transparent', // Placeholder color
    resizeMode: 'contain',
    alignSelf: 'center',
  },
  postBody: {
    width: SW(90),
    height: SH(20),
    marginTop: SH(2),
  },
  postnameText: {
    fontSize: RF(1.8),
    fontFamily: fonts.PoppinsSemiBold,
    color: colors.BLACK_COLOR,
    marginTop: SH(2),
  },
  postDateText: {
    fontSize: RF(1.4),
    fontFamily: fonts.PoppinsRegular,
    color: colors.MAIN_THEME_COLOR,

  },
  postContent: {
    width: SW(90),
    height: 'auto',
    backgroundColor: colors.WHITE_COLOR,
    alignSelf: 'center',
    marginBottom: SH(1),
    borderBottomLeftRadius: 6,
    borderBottomRightRadius: 6,
  },
  contentText: {
    fontSize: RF(1.8),
    fontFamily: fonts.PoppinsRegular,
    color: colors.BLACK_COLOR,
    marginTop: SH(2),
    textAlign: 'justify',
    marginHorizontal: SW(8),
    marginBottom: SH(1),
  },
  date_st:{
    fontSize: RF(1.4),
    fontFamily: fonts.PoppinsSemiBold,
    color: colors.BLACK_COLOR,
    textAlign: 'center',
    marginTop: SH(1),
  },
  deleteBtnImage:{
    width: SW(6),
    height: SW(6),
    resizeMode: 'contain',
    alignSelf: 'center',
  },
  deleteBtn:{
    width: SW(8),
    height: SW(8),
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    alignSelf: 'center',
    top: SH(49),
    right: SW(6),
  },

  //////////
  container2: {
    flex: 1,
    backgroundColor: colors.WHITE_COLOR_80,
  },
  header2: {
    marginTop: 50,
    marginBottom: 20,
    flexDirection: 'row',
    width: '90%',
    justifyContent: 'center',
    marginHorizontal: '5%',
  },
  headerText2: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colors.MAIN_THEME_COLOR,
    fontFamily: fonts.PoppinsSemiBold,
    alignSelf: 'center',
  },
  editBtn: {
    width: 24,
    height: 24,
    position: 'absolute',
    right: 50,
    top: 50,
  },
  editIcon: {
    width: 24,
    height: 24,
  },
  profilePic2: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: 'gray', // Placeholder color
    alignSelf: 'center',
  },
  infoContainer: {
    width: '90%',
    marginTop: '10%',
    marginBottom: '20%',
    marginHorizontal: '5%',
  },
  infoBox: {
    backgroundColor: colors.WHITE_COLOR,
    borderRadius: 10,
    padding: 15,
    marginBottom: 10,
    shadowColor: colors.MAIN_THEME_COLOR,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 20,
  },
  infoLabel: {
    color: colors.MAIN_THEME_COLOR,
    fontSize: 16,
    fontFamily: fonts.PoppinsSemiBold,
    marginLeft: 10,
  },
  infoContent: {
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    fontFamily: fonts.PoppinsSemiBold,
    color: colors.BLACK_COLOR,
  },
  button: {
    marginHorizontal: '10%',
    backgroundColor: colors.MAIN_THEME_COLOR,
    padding: 15,
    borderRadius: 20,
    width: '80%',
    alignItems: 'center',
    marginTop: 10,
    shadowColor: colors.BLACK_COLOR,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  buttonText: {
    color: colors.WHITE_COLOR,
    fontSize: 16,
  },
  noPostText: {
    fontSize: 20,
    color: colors.MAIN_THEME_COLOR,
    fontFamily: fonts.PoppinsSemiBold,
    textAlign: 'center',
    marginTop: SH(40),
  },
  noPostText_D: {
    fontSize: 20,
    color: colors.MAIN_THEME_COLOR,
    fontFamily: fonts.PoppinsSemiBold,
    textAlign: 'center',
  },
  noPost: {
    width: SW(90),
    height:SH(30),
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.MAIN_THEME_COLOR_50,
    borderRadius: 10,
  },
  noPost_G: {
    width: SW(90),
    height:SH(40),
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.MAIN_THEME_COLOR_50,
    borderRadius: 10,
    marginTop: SH(2),
  },
  modalBtns:{
    width: SW(80),
    height: SH(6),
    marginTop: SH(1),
    alignItems: 'flex-start',
    flexDirection: 'row',
    padding: SW(1),
  },
  modalsubText: {
    width: SW(70),
    marginTop: SH(5),
    height: SH(30),
    fontSize: RF(1.8),
    fontFamily: fonts.PoppinsSemiBold,
    color: colors.BLACK_COLOR_90,
    textAlign: 'justify',
  },
  dashCard: {
    width: SW(90),
    height: SH(53),
    backgroundColor: colors.WHITE_COLOR,
    borderRadius: 10,
    alignSelf: 'center',
    marginTop: SH(2),
    shadowColor: colors.MAIN_THEME_COLOR,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  

  
  



});